apiVersion: v1
kind: Namespace
metadata:
  name: cropps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: cropps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cropps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: plantdata
            - name: POSTGRES_USER
              value: cropps
            - name: POSTGRES_PASSWORD
              value: cropps123
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: cropps
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cropps-img
  namespace: cropps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cropps-img
  template:
    metadata:
      labels:
        app: cropps-img
    spec:
      containers:
        - name: cropps-img
          image: cropps-img:latest
          imagePullPolicy: Never
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DB_NAME
              value: plantdata
            - name: DB_USER
              value: cropps
            - name: DB_PASSWORD
              value: cropps123
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
          volumeMounts:
            - name: shared-images
              mountPath: /app/shared-images
      volumes:
        - name: shared-images
          hostPath:
            path: /mnt/c/Users/17177/Desktop/cropps-img-half/cropps-img/shared-images
            type: Directory